spring:
  profiles:
    active: dev
  #设置thymeleaf模板渲染
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  web:
    resources:
      static-locations: classpath:/static/,classpath:/templates/

